/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "content",

    {
      type: "category",
      label: "Programming",
      items: [
        {
          type: "category",
          label: "Containers, Kubernetes and OpenShift",
          items: [
            {
              type: "autogenerated",
              dirName: "programming/cko/section1",
            },
            {
              type: "autogenerated",
              dirName: "programming/cko/section2",
            },
            {
              type: "autogenerated",
              dirName: "programming/cko/section3",
            },
            {
              type: "autogenerated",
              dirName: "programming/cko/section4",
            },
          ],
        },
        {
          type: "autogenerated",
          dirName: "programming/shell"
        }, {
          type: "category",
          label: "NextJS",
          items: [
            {
              type: "autogenerated",
              dirName: "programming/nextjs/compilation"
            },
            {
              type: "autogenerated",
              dirName: "programming/nextjs/rendering"
            },
            {
              type: "autogenerated",
              dirName: "programming/nextjs/networking"
            }
          ]
        }
      ],
    },
    {
      type: "category",
      label: "Books",
      items: [
        { type: "doc", id: "books/backlog" },
        {
          type: "autogenerated",
          dirName: "books/book1",
        },
        { type: "autogenerated", dirName: "books/book2" },
      ],
    },
  ],
};

module.exports = sidebars;
