// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  docs: [
    "content",

    {
      type: "category",
      label: "Backend",
      items: [
        {
            type: "category",
            label: "General",
            items: [
                {
                    type: "doc",
                    id: "backend/general_db_concepts/dbdwdl"
                }
            ]
        }
        ,{
          type: "category",
          label: "Relational Databases",
          items: [
            {
                type: "category",
                label: "Indexing",
                items: [
                    {
                        type: "doc",
                        id: "backend/relational_db/indexing/intro"
                    },
                    {
                        type: "doc",
                        id: "backend/relational_db/indexing/disk_structure"
                    },
                    {
                        type: "doc",
                        id: "backend/relational_db/indexing/indexing"
                    }
                ]
            }
          ]
        },
        {
            type: "category",
            label: "Redis",
            items: [
                
            ]
        },
        {
            type: "category",
            label: "AspectJ",
            items: [
                {type: "doc", id: "backend/aspectj/comparison"},                 
                {type: "category", label: "AspectJ with Spring", items: [
                {
                  type: "doc", id: "backend/aspectj/spring_aspectj/overview"
                },
                    {
                      type: "doc", id: "backend/aspectj/spring_aspectj/pointcut"
                    },
                    {
                      type: "doc", id: "backend/aspectj/spring_aspectj/advice"
                    },
                    {
                      type: "doc", id: "backend/aspectj/spring_aspectj/introduction"
                    }
              ] },
                {type: "doc", id: "backend/aspectj/chapter1"},                 
                {type: "doc", id: "backend/aspectj/chapter2"},                 
                   ]
        }
        
      ],
     },
     {
      type: "category",
      label: "Frontend",
      items: [
        {
            type: "category",
            label: "Web",
            items: [
                {
          type: "category",
          label: "NextJS",
          items: [
            {
              type: "autogenerated",
              dirName: "frontend/web/nextjs/compilation"
            },
            {
              type: "autogenerated",
              dirName: "frontend/web/nextjs/rendering"
            },
            {
              type: "autogenerated",
              dirName: "frontend/web/nextjs/networking"
            }
          ]
        }    
            ]
        },
        {
            type: "category",
            label: "CSS",
            items: [
                {
                    type: "doc",
                    id: "frontend/css/units"
                }, 
                {
                    type: "doc",
                    id: "frontend/css/grid"
                },
                {
                    type: "doc",
                    id: "frontend/css/flexbox"
                },
            ]
        }
        
      ],
    },
    {
      type: "category",
      label: "Books",
      items: [
        { type: "autogenerated", dirName: "books/refactoring" },
        { type: "category", label: "JVM", items: [
    {type: "doc" ,id: "books/jvm/jvm-1"},
    {type: "doc" ,id: "books/jvm/jvm-2"},
    {type: "doc" ,id: "books/jvm/jvm-3-1"},
    {type: "doc" ,id: "books/jvm/jvm-3-2"},
        ] },
      ],
    },
    {
      type: "category",
      label: "Others",
      items: [
        { type: "doc", id: "others/vim/index" },
      ],
    },
  ],
};

module.exports = sidebars;
