name: deployment-actions

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: redkubes/docusaurus-deploy-action@v1
        with:
          source-folder: www
          git-user: chanjunren
          git-password: ${{ secrets.GITHUB_TOKEN }}
          deployment-branch: gh-pages
