name: deployment-actions

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@master
    
      - uses: actions/setup-node@master
        with:
          node-version: 18

      - name: Installing packages...
        run: npm i --force

      - name: Deploying...
        run: npm run deploy
