name: deployment-actions

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@master
    
      - uses: actions/setup-node@master
        with:
          node-version: 18

      - name: Installing packages...
        run: npm i --force

      - name: Build the app
        run: npm run build && npm run export && touch ./out/.nojekyll

      - name: Deploying...
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
